name: pertanian
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Cached network image
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  # Functional programming thingies
  dartz: ^0.10.1
  #http tools
  dio: ^4.0.6
  # debouncer
  easy_debounce: ^2.0.2+1
  # equatable for bloc
  equatable: ^2.0.3
  # flutter_bloc for widget bloc_test:
  flutter_bloc: ^8.1.1
  # native splash screen
  flutter_native_splash: ^2.2.7
  #for screen util (responsive)
  flutter_screenutil: ^5.5.3+2
  #for svg picture asset
  flutter_svg: ^1.1.5
  #for freezed annotiation
  freezed_annotation: ^1.1.0
  # GetX for route, state & dependency management
  get: ^4.6.5
  # Service locator
  get_it: ^7.2.0
  # No SQL local storage
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  # Image picker
  image_picker: ^0.8.4+10
  # contains code to deal with internationalized/localized
  intl: ^0.17.0
  # a convenient code generator for get_it
  injectable: ^1.5.3
  # Permission handler
  permission_handler: ^9.2.0
  # Getting commonly used locations on host platform file systems
  path_provider: ^2.0.11
  # Charts library
  syncfusion_flutter_charts: ^20.3.48
  # launching a URL
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  injectable_generator: ^1.5.3
  hive_generator: ^1.1.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
